// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXjtRzqGDP81gHjFHHyI6YZUa2CuL-Glk',
    appId: '1:248492920225:android:fc8bdb3d7a7fd0085bcfe0',
    messagingSenderId: '248492920225',
    projectId: 'coursaty-510e0',
    storageBucket: 'coursaty-510e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6kFVKe2mIxbA-DxOE4W-4fNXziGoa0yw',
    appId: '1:248492920225:ios:e379ae79c5bb39945bcfe0',
    messagingSenderId: '248492920225',
    projectId: 'coursaty-510e0',
    storageBucket: 'coursaty-510e0.firebasestorage.app',
    iosBundleId: 'com.YamanKartal.coursatyApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaJcz3YoDx0l1tnIo43RhhID3vv6I2jCs',
    appId: '1:248492920225:web:2d62acada6e00be85bcfe0',
    messagingSenderId: '248492920225',
    projectId: 'coursaty-510e0',
    authDomain: 'coursaty-510e0.firebaseapp.com',
    storageBucket: 'coursaty-510e0.firebasestorage.app',
    measurementId: 'G-7VTGKZGWMJ',
  );
}
